# ninelore's alacritty config

env:
  TERM: xterm-256color

window:
  padding:
    x: 4
    y: 4
  decorations_theme_variant: dark
  opacity: 0.7

scrolling:
  history: 2000
  multiplier: 1

font:
  normal: 
    family: Cascadia Mono
    style: Regular
  bold:
    family: Cascadia Mono
    style: Bold
  italic:
    family: Cascadia Mono
    style: Italic
  bold_italic:
    family: Cascadia Mono
    style: Bold Italic
  size: 11.0

colors:
  primary:
    background: '#161925'
    foreground: '#dcdfe1'
  normal:
    black:   '#161925'
    red:     '#ed254e'
    green:   '#71f79f'
    yellow:  '#f9dc5c'
    blue:    '#00c1e4'
    magenta: '#c74ded'
    cyan:    '#00d1a6'
    white:   '#c3c7d1'
  bright:
    black:   '#282c34'
    red:     '#ed254e'
    green:   '#71f79f'
    yellow:  '#f9dc5c'
    blue:    '#00c1e4'
    magenta: '#c74ded'
    cyan:    '#00d1a6'
    white:   '#dcdfe4'

cursor:
  style: Underline
  vi_mode_style: Block

hints:
  mouse:
    enabled: true
