# ninelore's alacritty config

env:
  TERM: xterm-256color

window:
  padding:
    x: 4
    y: 4
  gtk_theme_variant: dark

scrolling:
  history: 2000
  multiplier: 1

font:
  size: 10.0

colors:
  primary:
    background: '#161925'
    foreground: '#dcdfe1'
  normal:
    black:   '#161925'
    red:     '#ed254e'
    green:   '#71f79f'
    yellow:  '#f9dc5c'
    blue:    '#00c1e4'
    magenta: '#c74ded'
    cyan:    '#00d1a6'
    white:   '#c3c7d1'
  bright:
    black:   '#282c34'
    red:     '#ed254e'
    green:   '#71f79f'
    yellow:  '#f9dc5c'
    blue:    '#00c1e4'
    magenta: '#c74ded'
    cyan:    '#00d1a6'
    white:   '#dcdfe4'

background_opacity: 0.7

cursor:
  style: Underline
  vi_mode_style: Block

hints:
  mouse:
    enabled: true
