# ninelore's alacritty config

env:
  TERM: xterm-256color

window:
  padding:
    x: 5
    y: 5
  decorations_theme_variant: Dark
  opacity: 0.9

scrolling:
  history: 2000
  multiplier: 1

font:
  normal: 
    family: JetBrainsMono Nerd Font
    style: Regular
  bold:
    family: JetBrainsMono Nerd Font
    style: Bold
  italic:
    family: JetBrainsMono Nerd Font    
    style: Italic
  bold_italic:
    family: JetBrainsMono Nerd Font
    style: Bold Italic
  size: 12.0

colors:
  primary:
    background: '#101114'
    foreground: '#dcdfe4'
  normal:
    black:   '#282c34'
    red:     '#e06c75'
    green:   '#98c379'
    yellow:  '#e5c07b'
    blue:    '#61afef'
    magenta: '#c678dd'
    cyan:    '#56b6c2'
    white:   '#dcdfe4'
  bright:
    black:   '#5a6374'
    red:     '#e06c75'
    green:   '#98c379'
    yellow:  '#e5c07b'
    blue:    '#61afef'
    magenta: '#c678dd'
    cyan:    '#56b6c2'
    white:   '#dcdfe4'  primary:
    background: '#101114'
    foreground: '#dcdfe4'
  normal:
    black:   '#282c34'
    red:     '#e06c75'
    green:   '#98c379'
    yellow:  '#e5c07b'
    blue:    '#61afef'
    magenta: '#c678dd'
    cyan:    '#56b6c2'
    white:   '#dcdfe4'
  bright:
    black:   '#5a6374'
    red:     '#e06c75'
    green:   '#98c379'
    yellow:  '#e5c07b'
    blue:    '#61afef'
    magenta: '#c678dd'
    cyan:    '#56b6c2'
    white:   '#dcdfe4'

cursor:
  style: Underline
  vi_mode_style: Block

hints:
  mouse:
    enabled: true
